name: Workflow for develop branch
on:
  push:
    branches:
      - develop
jobs:

  IntegrationTests:
    name: Integration Test
    runs-on: ubuntu-20.04

    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: world
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/world
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        run: mvn test

      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)

  Build:
    name: Build and Run with Docker Compose
    runs-on: ubuntu-20.04
    needs: IntegrationTests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Docker Compose
        run: docker compose up -d